Login/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = "Login"

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('user_create/', views.CreateView.as_view(), name='user_create'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('perfil/', views.perfil, name='perfil'),  
    path('editar/perfil/', views.edit_profile, name='edit_profile'),
    path('perfil/<str:username>/', views.perfil, name='perfil'), 
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Main/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'Main'

urlpatterns = [
    path('', views.home, name='home'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Main.urls')),
    path('', include('Login.urls')),
    path('', include('Series.urls')),
    path('', include('Friends.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Series/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'Series'

urlpatterns = [
    path('serie/', views.SerieListView.as_view(), name='serie_list'), 
    path('serie/<int:id>/', views.SerieDetailView.as_view(), name='serie_details'),
    path('serie/create',views.serie_create, name="serie_create"),
    path('serie/update/<int:id>/', views.serie_update, name='serie_update'),
    path('serie/delete/<int:id>/', views.serie_delete, name='serie_delete'),
    path('serie/save/<int:id>/', views.serie_save, name='serie_save'),
    path('saved/', views.serie_saved_list, name='serie_saved_list'),
    path('opinion/<int:id>/borrar/', views.borrar_opinion, name='borrar_opinion'),
    path('serie/<str:genero_nombre>/', views.genero_list, name='genero_list'), 




]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Series/models.py
from django.db import models
from multiselectfield import MultiSelectField  
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.exceptions import ValidationError

class Generos(models.Model):
    genero = models.CharField(max_length=200)

    def __str__(self):
        return self.genero


class Serie(models.Model):
    PLATAFORMA_CHOICES = [
        ('flow', 'Flow'),
        ('disney_plus', 'Disney Plus'),
        ('max', 'Max'),
        ('amazon_prime', 'Amazon Prime'),
        ('paramount', 'Paramount'),
        ('apple_tv', 'Apple TV'),
        ('netflix', 'Netflix'),
        ('Youtube TV', 'Youtube TV'),
    ]
    
    titulo = models.CharField(max_length=200)
    descripcion = models.TextField(blank=True, null=True)  
    generos = models.ManyToManyField('Generos', through='SerieGenero', blank=True)  
    fecha_lanzamiento = models.DateTimeField(auto_now_add=True)  
    reparto = models.CharField(max_length=255, default="Desconocido", blank=True, null=True)  
    temporada = models.IntegerField(blank=True, null=True) 
    plataformas = MultiSelectField(choices=PLATAFORMA_CHOICES, blank=True, null=True) 
    imagen = models.ImageField(upload_to='Series/', blank=True, null=True) 
    
    def __str__(self):
        return self.titulo

class SerieGenero(models.Model):
    serie = models.ForeignKey(Serie, on_delete=models.CASCADE)
    genero = models.ForeignKey(Generos, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('serie', 'genero')  # Evita duplicados

class SerieGuardada(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    serie = models.ForeignKey(Serie, on_delete=models.CASCADE)
    class Meta:
        unique_together = ('usuario', 'serie')

class Opinion_serie(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    serie = models.ForeignKey('Serie', on_delete=models.CASCADE)
    opinion = models.CharField(max_length=1000)
    estrellas = models.IntegerField()
    

    def save(self, *args, **kwargs):
        print(f"Guardando opinión de {self.usuario} sobre {self.serie}")
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.usuario} - {self.serie} - {self.estrellas} estrellas"

Series/forms.py
from django import forms
from .models import Serie, Opinion_serie, Generos
from django.core.validators import MinValueValidator, MaxValueValidator

ESTRELLAS_CHOICES = [
        (1, "⭐ 1"),
        (2, "⭐ 2"),
        (3, "⭐ 3"),
        (4, "⭐ 4"),
        (5, "⭐ 5"),
    ]
class SerieForm(forms.ModelForm):
    generos = forms.ModelMultipleChoiceField(
        queryset=Generos.objects.all(),  # Carga todos los géneros disponibles
        widget=forms.CheckboxSelectMultiple(),  # Usa checkboxes para seleccionar múltiples
        required=False  # No es obligatorio elegir un género
    )

    class Meta:
        model = Serie
        fields = ["titulo", "descripcion", "generos", "temporada", "reparto", "imagen", "plataformas"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance.pk:  # Si la serie ya existe, preseleccionamos sus géneros
            self.fields["generos"].initial = self.instance.generos.all()
class GeneroForm(forms.ModelForm):
    class Meta:
        model = Generos
        fields = ['genero']
class OpinionSerieForm(forms.ModelForm):
  

    class Meta:
        model = Opinion_serie
        fields = ['opinion', 'estrellas']
        widgets = {
            'opinion': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 3,
                'placeholder': 'Escribe tu opinión aquí...'
            }),
            'estrellas': forms.Select(choices=ESTRELLAS_CHOICES, attrs={'class': 'form-select'})
        }

    estrellas = forms.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)],
        widget=forms.Select(choices=ESTRELLAS_CHOICES, attrs={'class': 'form-select'})
    )

Series/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
from django.urls import reverse_lazy
from .models import Serie, SerieGuardada, Opinion_serie, Generos
from .forms import SerieForm, OpinionSerieForm, GeneroForm
from django.views.generic import ListView, DetailView, DeleteView
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin



def is_superuser(user):
    return user.is_superuser

def serie_update(request, id):
    serie = Serie.objects.get(id=id)

    if request.method == "POST":
        form = SerieForm(request.POST, request.FILES, instance=serie)

        if form.is_valid():
            serie = form.save(commit=False)  # Guardamos la serie pero sin afectar aún la relación ManyToMany
            serie.save()
            form.save_m2m()  # Guardamos la relación ManyToMany correctamente

            return redirect("Series:serie_list")

    else:
        form = SerieForm(instance=serie)

    return render(request, 'Series/serie_update.html', context={"form": form, "serie": serie})

def serie_delete(request,id):
    serie = get_object_or_404(Serie, id=id)
    if request.method=="POST":
        serie.delete()
        return redirect("Series:serie_list")
    return render(request, 'Series/serie_delete.html', {"serie":serie})


class SerieListView(ListView):
    model = Serie
    template_name = "Series/serie_list.html"
    context_object_name = "serie"

    def get_queryset(self):
        queryset = super().get_queryset()
        busqueda = self.request.GET.get("busqueda", None)
        if busqueda:
            queryset = queryset.filter(titulo__icontains=busqueda)
        queryset = queryset.order_by('titulo')
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['series_guardadas_ids'] = list(
                SerieGuardada.objects.filter(usuario=self.request.user).values_list('serie_id', flat=True)
            )
        else:
            context['series_guardadas_ids'] = []
        return context
    


class SerieDetailView(DetailView):
    model = Serie
    template_name = 'Series/serie_detail.html'
    context_object_name = 'serie'

    def get_object(self):
        return Serie.objects.get(id=self.kwargs['id'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        serie = self.get_object()
        context['form_opinion'] = OpinionSerieForm()
        context['opiniones'] = Opinion_serie.objects.filter(serie=serie)
        if self.request.user.is_authenticated:
            context['series_guardadas_ids'] = list(
                SerieGuardada.objects.filter(usuario=self.request.user).values_list('serie_id', flat=True)
            )
        else:
            context['series_guardadas_ids'] = []
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('Login:login') 

        serie = self.get_object()
        form_opinion = OpinionSerieForm(request.POST)
        
        if form_opinion.is_valid():
            existing_opinion = Opinion_serie.objects.filter(usuario=request.user, serie=serie).first()

            if existing_opinion:
                # Si ya existe, actualizar la opinión
                existing_opinion.opinion = form_opinion.cleaned_data['opinion']
                existing_opinion.save()
            else:
                # Guardar la nueva opinión
                opinion = form_opinion.save(commit=False)
                opinion.usuario = request.user
                opinion.serie = serie
                opinion.save()

            return redirect('Series:serie_details', id=serie.id)

        return self.render_to_response({'form_opinion': form_opinion})
    
    

@login_required
def borrar_opinion(request, id):
    opinion = get_object_or_404(Opinion_serie, id=id, usuario=request.user)
    serie_id = opinion.serie.id
    opinion.delete()
    return redirect(request.META.get('HTTP_REFERER', request.path))
    
@user_passes_test(is_superuser)    
@login_required  
def serie_create(request):
    if request.method == "POST":
        form = SerieForm(request.POST, request.FILES) 
        if form.is_valid():
            serie = form.save(commit=False)
            serie.save()  
            return redirect('Series:serie_list')  
        else:
            return render(request, 'Series/serie_create.html', {'form': form})
    else:
        form = SerieForm()
    
    return render(request, 'Series/serie_create.html', {'form': form})

@login_required
def serie_save(request, id):
    serie = get_object_or_404(Serie, id=id)
    guardado = SerieGuardada.objects.filter(usuario=request.user, serie=serie)

    if guardado.exists():
        guardado.delete()
        messages.success(request, "La serie ha sido desguardada.")
    else:
        SerieGuardada.objects.create(usuario=request.user, serie=serie)
        messages.success(request, "La serie ha sido guardada.")

    return redirect(request.META.get('HTTP_REFERER', request.path))

def serie_saved_list(request):
    series_guardadas = SerieGuardada.objects.filter(usuario=request.user)
    return render(request, 'Series/serie_saved_list.html', {'series_guardadas': series_guardadas})



def genero_list(request, genero_nombre):
    genero = get_object_or_404(Generos, genero=genero_nombre)
    series = Serie.objects.filter(generos=genero).order_by('titulo')

    context = {
        "genero": genero,
        "series": series
    }
    return render(request, 'Series/serie_list_genero.html', context)

Series/templates/Series/serie_create.html
{% extends 'Main/base.html' %}   

{% block title %}
    Crear
{% endblock title %}

{% block title_content %}
    <h1 class="text-light text-center mb-4">✍️ Crear Serie</h1>
{% endblock title_content %}

{% block content %}
<style>
    body {
        background: linear-gradient(135deg, #1f1c2c, #928dab);
        color: white;
    }

    .card-custom {
        background: rgba(0, 0, 0, 0.8);
        border-radius: 15px;
        box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.5);
    }

    .form-control, .form-select {
        background: rgba(255, 255, 255, 0.1);
        border: 1px solid rgba(255, 255, 255, 0.3);
        color: white;
        border-radius: 10px;
    }

    .form-control:focus, .form-select:focus {
        background: rgba(255, 255, 255, 0.2);
        border-color: #ff8c00;
        box-shadow: 0 0 8px #ff8c00;
    }

    label {
        font-weight: bold;
        color: #ffcc70;
    }

    .btn-custom {
        background: linear-gradient(90deg, #ff8c00, #ff3d00);
        border: none;
        color: white;
        font-weight: bold;
        padding: 10px;
        border-radius: 10px;
        transition: 0.3s ease-in-out;
    }

    .btn-custom:hover {
        transform: scale(1.05);
        background: linear-gradient(90deg, #ff3d00, #ff8c00);
    }

    .btn-cancel {
        background: transparent;
        border: 1px solid white;
        color: white;
        transition: 0.3s ease-in-out;
    }

    .btn-cancel:hover {
        background: white;
        color: black;
    }
    #id_genero{
        color: rgb(255, 255, 255);
    }
    #id_genero:hover{
        color: black;
    }
    .boton-fijo {
    position: fixed;
    bottom: 50px; 
    right: 40px;   
    z-index: 1000; 
}
</style>

<div class="container mt-5 d-flex justify-content-center">
    <div class="col-md-8">
        <div class="card card-custom p-4">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="mb-4">
                        <label for="id_titulo">🎬 Título</label>
                        {{ form.titulo }}
                    </div>
                    
                    <div class="mb-4">
                        <label for="id_descripcion">📝 Descripción</label>
                        {{ form.descripcion }}  
                    </div>

                    <div class="mb-4">
                        <label for="id_generos">📌 Géneros</label>
                        {{ form.generos }}
                    </div>

                    <div class="mb-4">
                        <label for="id_temporada">📅 Temporada</label>
                        {{ form.temporada }}
                    </div>

                    <div class="mb-4">
                        <label for="id_reparto">🎭 Reparto</label>
                        {{ form.reparto }}
                    </div>
                    
                    <div class="mb-4">
                        <label for="id_imagen">📷 Imagen</label>
                        {{ form.imagen }}
                    </div>
                    <div class="mb-4">
                        <label for="id_plataforma"> Plataforma</label>
                        {{ form.plataformas }}
                    </div>

                    <div class="d-flex justify-content-between">
                        <button onclick="window.history.back()" class="btn btn-custom w-45 shadow-sm">Crear</button>
                    </div>
                    
                    <div class="text-end mt-3">
                        <a href="{{ request.META.HTTP_REFERER|default:'' }}" class="btn btn-cancel">Cancelar</a>
                    </div>
                </form>
            </div>
            <div>
            <button onclick="window.history.back()" class="btn btn-primary boton-fijo">Volver</button>
        </div>
        </div>
        
    </div>
</div>  

{% endblock content %}

Series/templates/Series/serie_detail.html
{% extends 'Main/base.html' %}
{% load static %}
{% get_media_prefix as media_url %}

{% block title %}{{ serie.titulo }} - Detalles{% endblock title %}

{% block content %}
<style>
.serie-container {
    position: relative;
    color: white;
    background: linear-gradient(to right, rgba(0, 0, 0, 0.8), rgba(0, 0, 0, 0.2));
    padding: 60px;
    border-radius: 15px;
}
.serie-bg {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: url('{{ serie.imagen.url }}') no-repeat center center/cover;
    filter: blur(15px);
    opacity: 0.4;
    z-index: -1;
    border-radius: 15px;
}
.serie-detalle {
    display: flex;
    align-items: center;
    gap: 30px;
}
.serie-detalle img {
    width: 350px;
    border-radius: 15px;
    box-shadow: 0px 5px 15px rgba(0,0,0,0.3);
}
.boton {
    padding: 12px 25px;
    border-radius: 25px;
    border: none;
    color: white;
    font-size: 18px;
    cursor: pointer;
    transition: 0.3s;
}
.boton.guardar { background-color: #0078ff; }
.boton.desguardar { background-color: #555; }
.boton:hover { opacity: 0.8; }
.botonera {
    display: flex;
    gap: 15px;
    margin-top: 20px;
}
.opiniones-container {
    margin-top: 40px;
    color: rgb(255, 255, 255);
}
.card-opinion {
    background: rgba(255, 255, 255, 0.1);
    padding: 20px;
    border-radius: 10px;
    margin-bottom: 20px;
}

.form-label {
    color: white;
}
.form-control {
    background-color: #f1f1f1;
    width: 60%;
    margin: 0 auto;
}
.stars-container {
    display: flex;
    justify-content: center;
    width: 60%;
    margin: 0 auto;
}
.btn-primary {
    background-color: #003366; /* Azul oscurito */
    width: auto;
    margin: 0 auto;
    display: block;
    padding: 10px 30px;
    border-radius: 25px;
}
.boton.actualizar{background-color: rgb(27, 4, 160); text-decoration: none;}
.boton.eliminar{background-color: rgb(110, 0, 0); text-decoration: none;}
.boton-fijo {
    position: fixed;
    bottom: 50px; 
    right: 40px;   
    z-index: 1000; 
}               
.user-opinion{text-decoration: none; color: white;}

</style>

<div class="serie-container">
    <div class="serie-bg"></div>
    <div class="serie-detalle">
        <img src="{{ serie.imagen.url }}" alt="Imagen de {{ serie.titulo }}">
        <div>
            <h1>{{ serie.titulo }}</h1>
            <p>{{ serie.descripcion }}</p>
            <p><strong>Géneros:</strong> {{ serie.generos.all|join:', ' }}</p>
            <p><strong>Temporadas:</strong> {{ serie.temporada }}</p>
            <p><strong>Reparto:</strong> {{ serie.reparto }}</p>
            <p><strong>Donde ver: </strong> {{ serie.plataformas|join:', ' }}</p>
            <div class="botonera">
            {% if user.is_superuser %}
                <a href="{% url 'Series:serie_update' id=serie.id %}" class="boton actualizar">Actualizar</a>
                <a href="{% url 'Series:serie_delete' id=serie.id %}" class="boton eliminar">Eliminar</a>
            {% else %}
                <form method="post" action="{% url 'Series:serie_save' id=serie.id %}" class="d-inline">
                    {% csrf_token %}
                    {% if serie.id in series_guardadas_ids %}
                        <button type="submit" class="boton desguardar">Desguardar</button>
                    {% else %}
                        <button type="submit" class="boton guardar">Guardar</button>
                    {% endif %}
                </form>
            {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="opiniones-container">
    <h2 class="text-center">Opiniones de la serie</h2>
    {% if opiniones %}
        <div>
            {% for opinion in opiniones %}
                <div class="card-opinion">
                    <a href="{% url 'Login:perfil' opinion.usuario.username %}" class="user-opinion">{{ opinion.usuario.username }}</a>
                    <p>{{ opinion.opinion }}</p>
                    <p>⭐ {{ opinion.estrellas }} / 5</p>
                    {% if user == opinion.usuario or user.is_superuser %}
                        <form action="{% url 'Series:borrar_opinion' opinion.pk %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger btn-sm">🗑️ Borrar Opinión</button>
                        </form>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p class="text-center">No hay opiniones todavía.</p>
    {% endif %}
</div>

<div class="mt-5">
    <h3 class="text-center text-light">Deja tu opinión</h3>
    <form method="POST" >
        {% csrf_token %}
        <div class="mb-3">

            {{ form_opinion.opinion }}
        </div>
        <div class="mb-3">

            <div class="stars-container">
                {{ form_opinion.estrellas }}
            </div>
        </div>
        <button type="submit" class="btn btn-primary">📩 Enviar Opinión</button>
    </form>
</div>    
<div>
    <a href="{% url 'Main:home' %}" class="btn btn-primary boton-fijo">Volver</a>
</div>

{% endblock %}

Series/templates/Series/serie_list.html
{% extends 'Main/base.html' %}

{% block title %}
    Lista de Series
{% endblock title %}

{% block title_content %}
{% endblock title_content %}

{% block content %}
<style>
.serie_contenedor {
    display: flex;
    flex-direction: column;  /* Organiza la imagen arriba y los botones abajo */
    align-items: center;
    width: 350px;
    height: auto;
    margin: auto;
    position: relative;
    overflow: hidden;
    transition: transform 0.3s ease; /* Para agrandar el contenedor */
}

.serie_contenedor:hover {
    transform: scale(1.1); /* Agranda el contenedor al pasar el cursor */
}

.serie_image {
    width: 100%;
    height: 300px;
    object-fit: cover;  /* Cubre el área sin deformarse */
    border-radius: 10px;
    transition: opacity 0.3s ease; /* Para hacer desaparecer el botón al hacer hover */
}

.titulo-serie {
    position: absolute;
    bottom: -30px; /* Empuja el título fuera de la vista */
    left: 0;
    width: 100%;
    text-align: center;
    color: white;
    background-color: rgba(0, 0, 0, 0.6);
    padding: 10px;
    opacity: 0;
    transition: all 0.3s ease; /* Transición para que el título aparezca */
}

.serie_contenedor:hover .titulo-serie {
    bottom: 0;
    opacity: 1;
}

.serie_contenedor:hover  + .botonera .guardar {
    display: none; /* Oculta los botones al hacer hover sobre la imagen */
}

.botonera {
    display: flex;
    justify-content: center;
    gap: 10px;
    margin-top: 10px;
}

.boton {
    display: inline-block;
    padding: 5px 15px;
    font-size: 14px;
    text-align: center;
    text-decoration: none;
    border-radius: 20px;
    border: none;
    color: white;
    cursor: pointer;
    transition: 0.3s;
    margin-top: 10px;
}

.boton:hover {
    opacity: 0.8;
}

.detalle {
    background-color: rgb(0, 65, 65);
}

.boton.actualizar{background-color: rgb(27, 4, 160); text-decoration: none;}

.boton.eliminar{background-color: rgb(110, 0, 0); text-decoration: none;}

.guardar {
    background-color: rgb(0, 24, 66);
}

.desguardar {
    background-color: rgb(54, 54, 54);
}

.boton-fijo {
    position: fixed;
    bottom: 50px; 
    right: 40px;   
    z-index: 1000; 
}
    
</style>

    <div class="container my-5">
        <div class="d-flex align-items-center mb-4" style="justify-content: center;">
            <form method="get" action="{% url 'Series:serie_list' %}" class="d-flex w-75">
                <input type="text" name="busqueda" placeholder="Buscar serie" value="{{ request.GET.busqueda }}" 
                    class="form-control me-2" style="border-radius: 20px; padding-left: 15px;">
                <button type="submit" class="btn" style="border-radius: 20px; background-color: rgb(54, 54, 54); color: white;">
                    <i class="bi bi-search"></i> Buscar
                </button>
            </form>    
        </div>

        <div class="row">
            {% if user.is_superuser %}
                <a href="{% url 'Series:serie_create' %}">Crear Serie</a>
            {% endif %}
            {% for serie in serie %}
                <div class="col-lg-4 col-md-6 col-sm-12 mb-4">
                    <div class="serie_contenedor">
                        <a href="{% url 'Series:serie_details' id=serie.id %}">
                            {% if serie.imagen %}
                                <img src="{{ serie.imagen.url }}" class="serie_image" alt="Imagen de {{ serie.titulo }}">
                            {% else %}
                                <div class="sin-imagen">Sin imagen disponible</div>
                            {% endif %}
                        </a>
                        <div class="titulo-serie">{{ serie.titulo }}</div>
                    </div>
        
                    <div class="botonera">
                        {% if user.is_superuser %}
                            <a href="{% url 'Series:serie_update' id=serie.id %}" class="boton actualizar">Actualizar</a>
                            <a href="{% url 'Series:serie_delete' id=serie.id %}" class="boton eliminar">Eliminar</a>
                        {% else %}
                            <form method="post" action="{% url 'Series:serie_save' id=serie.id %}" class="d-inline">
                                {% csrf_token %}
                                {% if serie.id in series_guardadas_ids %}
                                    <button type="submit" class="boton desguardar">Desguardar</button>
                                {% else %}
                                    <button type="submit" class="boton guardar">Guardar</button>
                                {% endif %}
                            </form>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <div>
        <a href="{% url 'Main:home' %}" class="btn btn-primary boton-fijo">Volver</a>
    </div>
    

{% endblock content %}

Series/templates/Series/serie_update.html
{% extends 'Main/base.html' %}   

{% block title %}
    Actualizar
{% endblock title %}

{% block title_content %}
    <h1 class="text-light text-center mb-4">✍️ Editar Reseña</h1>
{% endblock title_content %}

{% block content %}
<style>
    body {
        background: linear-gradient(135deg, #1f1c2c, #928dab);
        color: white;
    }

    .card-custom {
        background: rgba(0, 0, 0, 0.8);
        border-radius: 15px;
        box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.5);
    }

    .form-control, .form-select {
        background: rgba(255, 255, 255, 0.1);
        border: 1px solid rgba(255, 255, 255, 0.3);
        color: white;
        border-radius: 10px;
    }

    .form-control:focus, .form-select:focus {
        background: rgba(255, 255, 255, 0.2);
        border-color: #ff8c00;
        box-shadow: 0 0 8px #ff8c00;
    }

    label {
        font-weight: bold;
        color: #ffcc70;
    }

    .btn-custom {
        background: linear-gradient(90deg, #ff8c00, #ff3d00);
        border: none;
        color: white;
        font-weight: bold;
        padding: 10px;
        border-radius: 10px;
        transition: 0.3s ease-in-out;
    }

    .btn-custom:hover {
        transform: scale(1.05);
        background: linear-gradient(90deg, #ff3d00, #ff8c00);
    }

    .btn-cancel {
        background: transparent;
        border: 1px solid white;
        color: white;
        transition: 0.3s ease-in-out;
    }

    .btn-cancel:hover {
        background: white;
        color: black;
    }
    #id_genero{
        color: rgb(255, 255, 255);
    }
    #id_genero:hover{
        color: black;
    }
    .boton-fijo {
    position: fixed;
    bottom: 50px; 
    right: 40px;   
    z-index: 1000; 
}
</style>

<div class="container mt-5 d-flex justify-content-center">
    <div class="col-md-8">
        <div class="card card-custom p-4">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="mb-4">
                        <label for="id_titulo">🎬 Título</label>
                        {{ form.titulo }}
                    </div>
                    
                    <div class="mb-4">
                        <label for="id_descripcion">📝 Descripción</label>
                        {{ form.descripcion }}  
                    </div>

                    <div class="mb-4">
                        <label for="id_generos">📌 Géneros</label>
                        {{ form.generos }}
                    </div>

                    <div class="mb-4">
                        <label for="id_temporada">📅 Temporada</label>
                        {{ form.temporada }}
                    </div>

                    <div class="mb-4">
                        <label for="id_reparto">🎭 Reparto</label>
                        {{ form.reparto }}
                    </div>
                    
                    <div class="mb-4">
                        <label for="id_imagen">📷 Imagen</label>
                        {{ form.imagen }}
                    </div>
                    <div class="mb-4">
                        <label for="id_plataforma"> Plataforma</label>
                        {{ form.plataformas }}
                    </div>

                    <div class="d-flex justify-content-between">
                        <button onclick="window.history.back()" class="btn btn-custom w-45 shadow-sm">Actualizar</button>
                        <a href="{% url 'Series:serie_delete' serie.pk %}" class="btn btn-danger w-45 shadow-sm">Eliminar</a>
                    </div>
                    
                    <div class="text-end mt-3">
                        <a href="{{ request.META.HTTP_REFERER|default:'' }}" class="btn btn-cancel">Cancelar</a>
                    </div>
                </form>
            </div>
            <div>
            <button onclick="window.history.back()" class="btn btn-primary boton-fijo">Volver</button>
        </div>
        </div>
        
    </div>
</div>  

{% endblock content %}