Friends/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import seguir_usuario, dejar_de_seguir_usuario, lista_seguidos, lista_seguidores, mi_red

app_name = "Friends"

urlpatterns = [
    path("seguir/<int:usuario_id>/", seguir_usuario, name="seguir_usuario"),
    path("dejar_de_seguir/<int:usuario_id>/", dejar_de_seguir_usuario, name="dejar_de_seguir"),
    path("seguidos/<str:username>/", lista_seguidos, name="lista_seguidos"),
    path('seguidores/<str:username>/', lista_seguidores, name='lista_seguidores'),
    path('mi_red/<str:username>/', mi_red, name='mi_red'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Login/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = "Login"

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('user_create/', views.CreateView.as_view(), name='user_create'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('perfil/', views.perfil, name='perfil'),  
    path('editar/perfil/', views.edit_profile, name='edit_profile'),
    path('perfil/<str:username>/', views.perfil, name='perfil'), 
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Main/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'Main'

urlpatterns = [
    path('', views.home, name='home'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Main.urls')),
    path('', include('Login.urls')),
    path('', include('Series.urls')),
    path('', include('Friends.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Series/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'Series'

urlpatterns = [
    path('serie/', views.SerieListView.as_view(), name='serie_list'), 
    path('serie/<int:id>/', views.SerieDetailView.as_view(), name='serie_details'),
    path('serie/create',views.serie_create, name="serie_create"),
    path('serie/update/<int:id>/', views.serie_update, name='serie_update'),
    path('serie/delete/<int:id>/', views.serie_delete, name='serie_delete'),
    path('serie/save/<int:id>/', views.serie_save, name='serie_save'),
    path('saved/', views.serie_saved_list, name='serie_saved_list'),
    path('opinion/<int:id>/borrar/', views.borrar_opinion, name='borrar_opinion'),
    path('serie/<str:genero_nombre>/', views.genero_list, name='genero_list'), 




]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Main/models.py
from django.db import models

Series/models.py
from django.db import models
from multiselectfield import MultiSelectField  
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.exceptions import ValidationError

class Generos(models.Model):
    genero = models.CharField(max_length=200)

    def __str__(self):
        return self.genero


class Serie(models.Model):
    PLATAFORMA_CHOICES = [
        ('flow', 'Flow'),
        ('disney_plus', 'Disney Plus'),
        ('max', 'Max'),
        ('amazon_prime', 'Amazon Prime'),
        ('paramount', 'Paramount'),
        ('apple_tv', 'Apple TV'),
        ('netflix', 'Netflix'),
        ('Youtube TV', 'Youtube TV'),
    ]
    
    titulo = models.CharField(max_length=200)
    descripcion = models.TextField(blank=True, null=True)  
    generos = models.ManyToManyField('Generos', through='SerieGenero', blank=True)  
    fecha_lanzamiento = models.DateTimeField(auto_now_add=True)  
    reparto = models.CharField(max_length=255, default="Desconocido", blank=True, null=True)  
    temporada = models.IntegerField(blank=True, null=True) 
    plataformas = MultiSelectField(choices=PLATAFORMA_CHOICES, blank=True, null=True) 
    imagen = models.ImageField(upload_to='Series/', blank=True, null=True) 
    
    def __str__(self):
        return self.titulo

class SerieGenero(models.Model):
    serie = models.ForeignKey(Serie, on_delete=models.CASCADE)
    genero = models.ForeignKey(Generos, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('serie', 'genero')  # Evita duplicados

class SerieGuardada(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    serie = models.ForeignKey(Serie, on_delete=models.CASCADE)
    class Meta:
        unique_together = ('usuario', 'serie')

class Opinion_serie(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    serie = models.ForeignKey('Serie', on_delete=models.CASCADE)
    opinion = models.CharField(max_length=1000)
    estrellas = models.IntegerField()
    

    def save(self, *args, **kwargs):
        print(f"Guardando opinión de {self.usuario} sobre {self.serie}")
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.usuario} - {self.serie} - {self.estrellas} estrellas"

Main/views.py
from django.shortcuts import render
from django.shortcuts import render
from Series.models import Serie, Generos
from django.db.models import Avg
import random

# Create your views here.

def home(request):
    series = Serie.objects.all()


    top_5_series = Serie.objects.annotate(promedio_estrellas=Avg('opinion_serie__estrellas')) \
    .order_by('-promedio_estrellas')[:5]

    generos = Generos.objects.prefetch_related('seriegenero_set').all()

    for genero in generos:
        series_genero = list(genero.seriegenero_set.all())  # me devuelve todas las series de tal genero
        random.shuffle(series_genero)  
        genero.series_aleatorias = random.sample(series_genero, min(10, len(series_genero)))


    return render(request, 'Main/home.html', {
        'series': series,
        'top_5_series': top_5_series,
        'generos': generos
    })

Main/templates/Main/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog | {% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;700&display=swap');

        body {
            font-family: 'Montserrat', sans-serif;
        }
    </style>
</head>
{% load static %}
{% get_media_prefix as media_url %}
<body style="background-color: #000000; ">
  <nav class="navbar navbar-expand-lg navbar-dark shadow-sm fixed-top" style="background-color: #343a40;">
    <div class="container-fluid" style="padding-right: 40px; padding-left: 100px;">
        <a class="navbar-brand fw-bold text-primary text-white" style="font-size:25px" href="{% url 'Main:home' %}">PILOTÓN</a>
        <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav ms-auto d-flex align-items-center">
                <li class="nav-item me-3">
                    <a class="nav-link active" href="{% url 'Main:home' %}">Inicio</a>
                </li>

                <!-- Buscador -->
                <li class="nav-item me-3">
                    <form method="get" action="{% url 'Series:serie_list' %}" class="d-flex">
                        <input type="text" name="busqueda" placeholder="Buscar serie" value="{{ request.GET.busqueda }}" style="border-radius: 20px; padding-left: 15px;">
                        <button type="submit" class="btn" style="border-radius: 20px; background-color: rgb(255, 255, 255); margin-left:10px;">
                            <img src="{% get_media_prefix %}logos/lupa.png" alt="" height="15px" width="15px">
                        </button>
                    </form>    
                </li>

                {% if user.is_authenticated %}

                    <li class="nav-item me-3">
                        <a class="nav-link active" href="{% url 'Series:serie_saved_list' %}">Mis series</a>
                    </li>
                    <li class="nav-item me-3">
                        <a class="nav-link active" href="{% url 'Friends:mi_red' user.username%}">Mi red</a>
                    </li>
                    

                    <li class="nav-item me-3">
                        <a class="nav-link" href="{% url 'Login:perfil' %}">
                            {% if user.avatar %}
                                <img src="{{ user.avatar.url }}" alt="Avatar" class="rounded-circle" width="30" height="30">
                            {% else %}
                                <img src="https://via.placeholder.com/30" alt="Avatar" class="rounded-circle" width="30" height="30">
                            {% endif %}

                        </a>
                    </li>

                    <li class="nav-item">
                        <form action="{% url 'Login:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="nav-link btn btn-link">Salir</button>
                        </form>
                    </li>
                {% else %}
                    <li class="nav-item me-3">
                        <a class="nav-link active" href="{% url 'Login:login' %}">Iniciar Sesión</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'Login:register' %}">Registrar</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

    <div class="mt-5" style="padding: 0px 20px;">
        <h1 class="text-center mb-4 " style="padding-top: 30px; color: white;">
          {% block title_content %}
            {% endblock title_content %}  
        </h1>
            
            {% block content %}
                
            {% endblock content %}
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
  <footer class="bg-dark text-white py-4 mt-5" style="background-color: #343a40;" style="margin-top: 2rem;">
    <div class="container text-center">
        <p class="mb-2">&copy; 2024 Mi Sitio Web. Todos los derechos reservados.</p>
        <ul class="nav justify-content-center">
            <li class="nav-item">
                <a class="nav-link" style="color: #85929e;" href="https://www.linkedin.com/in/agustin-cancelare-m-a9a1922b0/">Acerca de</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" style="color: #85929e;" href="#">Política de Privacidad</a>
            </li>
        </ul>
    </div>
  </footer>


</html>

Main/templates/Main/home.html
{% extends 'Main/base.html' %}
{% block title %}
    Home
{% endblock title %}

{% block content %}

<style>
@import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;700&display=swap');

body {
    font-family: 'Montserrat', sans-serif;
}

.genero_titulo_contenedor {
    display: flex;
    align-items: center; /* Alinea verticalmente */
    gap: 15px; /* Espacio entre el título y "Explorar todas" */
}

.explorar_mas {
    text-decoration: none; /* Quita el subrayado */
    color: rgb(104, 104, 104);
    font-size: 1em;
    transition: color 0.3s ease;
}

.explorar_mas:hover {
    color: rgb(255, 255, 255);
    transition: 0.5s;
}
.serie_contenedor {
    display: flex;
    flex-direction: column;
    align-items: center;
    width: 350px;
    height: 250px;
    margin: auto;
    position: relative;
    overflow: visible;  
    transition: transform 0.3s ease;
    z-index: 1; 
    justify-content: center;
}

.serie_contenedor:hover {
    transform: scale(1.10); 
    z-index: 10;
}

.generos_home {
    display: flex;
    flex-wrap: nowrap;
    overflow-x: auto;
    overflow-y: hidden;
    gap: 15px;
    padding-bottom: 15px;
    scroll-snap-type: x mandatory;
    -webkit-overflow-scrolling: touch;
    white-space: nowrap;
    position: relative;
    padding-top: 15px;
}

.series_imagenes {
    width: 100%;
    height: 100%; 
    object-fit: cover; 
    border-radius: 10px;
    transition: opacity 0.3s ease; 
}

.titulo-serie {
    position: absolute;
    bottom: -30px; /* Empuja el título fuera de la vista */
    left: 0;
    width: 100%;
    text-align: center;
    color: white;
    background-color: rgba(0, 0, 0, 0.6);
    padding: 10px;
    opacity: 0;
    transition: all 0.3s ease; /* Transición para que el título aparezca */
}
.contenedor_generos{
    margin-left: 50px;
    margin-right: 50px;    
}
.contenedor_generos .generos_home {
    overflow-y: hidden; /* Elimina el scroll vertical */
    max-height: 250px; /* Limita la altura máxima */
}

.contenedor_generos .serie_contenedor {
    width: 350px;
    height: auto; /* Altura dinámica */
    overflow: hidden;
}

.contenedor_generos .series_imagenes {
    width: 100%;
    height: auto;
    max-height: 250px;
    aspect-ratio: 16/9; /* Mantiene una proporción adecuada */
    object-fit: cover;  /* Cubre el área sin deformarse */
    border-radius: 10px;
}


.serie_contenedor:hover .titulo-serie {
    bottom: 0;
    opacity: 1; /* Hace visible el título al hacer hover */
}.genero_titulo_contenedor {
    display: flex;
    align-items: center; /* Alinea verticalmente */
    justify-content: space-between; /* Separa los elementos */
    gap: 15px; /* Espacio entre el título y "Explorar más" */
}



.scroll-button {
    position: absolute;
    top: 50%;
    transform: translateY(-50%);
    width: 40px;
    height: 40px;
    border: none;
    background-color: rgba(87, 77, 77, 0.7);
    color: white;
    border-radius: 50%;
    cursor: pointer;
    z-index: 1000; /* Más alto que cualquier imagen */
    opacity: 1; /* Siempre visible */
    visibility: visible; /* Siempre visible */
    transition: background-color 0.3s ease-in-out;
}

.position-relative:hover .scroll-button {
    opacity: 1;
    visibility: visible;
}

.d-flex.overflow-auto {
    overflow: hidden; 
}
.d-flex.overflow-auto::-webkit-scrollbar {
    display: none; 
}
.genero_tittle{
        color: white;
        font-family: 'Poppins', sans-serif;
        margin-top: 35px;
        margin-bottom: 35px;
        font-size: 2em;
}
.serie_image {
    width: 100%;
    height: 100%;
    object-fit: cover;
    border-radius: 10px;
    transition: opacity 0.3s ease;
}

.recomendacion_contenedor{
    background-color: red;
    height: 70vh;
    width: 60dvw;
}
.recomendacion_image{
    object-fit: cover;
    width: 100%;
    height: 100%;

}

.generos_home::-webkit-scrollbar {
    display: none;
}
.scroll-button.left {
    left: 10px;
}
.scroll-button.right {
    right: 10px ;
}
.scroll-button:hover {
    background-color: rgba(0, 0, 0, 0.8);
}
.serie_card {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: space-between;
    box-shadow: 0 4px 8px rgba(158, 50, 50, 0.1);
    height: 370px;
    border-radius: 10px;
    padding: 10px;
    background-color: rgb(44, 44, 44);
}
.position-relative:hover .scroll-button {
    opacity: 1;
    visibility: visible;
}
</style>
<script>
    function scrollContent(direction, button) {
        const container = button.parentElement.querySelector('.generos_home');
        const scrollAmount = 800;
        
        if (container) {
            if (direction === 'left') {
                container.scrollBy({ left: -scrollAmount, behavior: 'smooth' });
            } else {
                container.scrollBy({ left: scrollAmount, behavior: 'smooth' });
            }
        }
    }
    const generosHome = document.querySelectorAll('.generos_home');

    generosHome.forEach((generos) => {
        generos.addEventListener('wheel', (e) => {
            e.preventDefault();
            generos.scrollLeft += e.deltaY; 
        });
    });
</script>
<div class="recomendaciones">
    <h1 style="padding-bottom: 20px; color: white; text-align: center;">SERIES CON MEJORES PUNTUACIONES</h1>
    <div class="position-relative">
        {% if top_5_series|length > 4 %}
            <button class="scroll-button left" onclick="scrollContent('left', this)">&lt;</button>
        {% endif %}
        <div class="generos_home">
            {% for serie in top_5_series %}

                <a href="{% url 'Series:serie_details' id=serie.id %}">
                    <div class="recomendacion_contenedor">
                        {% if serie.imagen %}
                            <img src="{{ serie.imagen.url }}" alt="Imagen de {{ serie.titulo }}" class="recomendacion_image">
                        {% else %}
                            <p style="color: white;">No hay imagen disponible.</p>
                        {% endif %}
                    </div>
                </a>

            {% endfor %}
        </div>

        {% if top_5_series|length > 4 %}
            <button class="scroll-button right" onclick="scrollContent('right', this)">&gt;</button>
        {% endif %}
    </div>
</div>

{% for genero in generos %}

    <div class="contenedor_generos">
        {% if genero.seriegenero_set.exists%}
            <div class="genero_titulo_contenedor">
                <h1 class="genero_tittle">{{ genero.genero }}</h1>
                <a href="{% url 'Series:genero_list' genero%}" class="explorar_mas">Explorar todas ></a>

            </div>
        
            <div class="position-relative" >
                {% if genero.seriegenero_set.all|length > 4 %}
                    <button class="scroll-button left" onclick="scrollContent('left', this)">&lt;</button>
                {% endif %}
    
                <div class="generos_home">
                    {% for seriegenero in genero.series_aleatorias %}
                    <a href="{% url 'Series:serie_details' id=seriegenero.serie.id %}">
                        <div class="serie_contenedor" >
                            {% if seriegenero.serie.imagen %}
                                <img src="{{ seriegenero.serie.imagen.url }}" alt="Imagen de {{ seriegenero.serie.titulo }}" class="series_imagenes">
                            {% else %}
                                <div class="sin-imagen">Sin imagen disponible</div>
                            {% endif %}
                
                            <div class="titulo-serie">{{ seriegenero.serie.titulo }}</div>
                        </div>
                    </a>
                {% endfor %}
                
                </div>
    
                {% if genero.seriegenero_set.all|length > 4 %}
                    <button class="scroll-button right" onclick="scrollContent('right', this)">&gt;</button>
                {% endif %}
            </div>
        {% endif %}
        
        
    </div>
{% endfor %}






{% endblock content %}

Main/templates/Main/index.html
{% extends 'Main/base.html' %}

{% block title %}
    Inicio
{% endblock title %}

{% block content_title %}
    Blog de turismo
{% endblock content_title %}

{% block content %}
    <div style="display: flex; justify-content: center; align-items: center; padding-top: 50px;">
        <a href="{% url 'Main:home' %}" class="btn btn-lg btn-info text-white">Ingresar</a>
    </div>
{% endblock content %}